services:
    # flask server
    flask-server:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
          - 8182:5000
        env_file:
          - ./.env
        networks:
          - app-network


    # celery worker
    celery-worker:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
          - ./.env
        depends_on:
            - flask-server
            - redis
        networks:
          - app-network

    # redis server
    redis:
        restart: unless-stopped
        image: redis:7.0.5-alpine 
        expose:
            - 6379
        networks:
          - app-network

          
networks:
  app-network:
    driver: bridge