"""Fix cascade on delete user

Revision ID: b623e91eeb1a
Revises: 
Create Date: 2024-08-25 18:30:27.804801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b623e91eeb1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('subscriptions')
    op.drop_table('user_subscriptions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscriptions',
    sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('subscription_id', mysql.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], name='user_subscriptions_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_subscriptions_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'subscription_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('subscriptions',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('subscription_name', mysql.VARCHAR(length=1024), nullable=False),
    sa.Column('subscription_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('subscription_cost', mysql.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('subscription_description', mysql.TEXT(), nullable=False),
    sa.Column('start_date', mysql.DATETIME(), nullable=False),
    sa.Column('expiry_date', mysql.DATETIME(), nullable=False),
    sa.Column('last_notification', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(length=60), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='subscriptions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
